project:
  type: website
  output-dir: docs

website:
  title: "Nicholas Nagle"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: fanart.qmd
        text: Fanart

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

